# Change these first
owner: Bart0110 # Your GitHub organization or username, where this repository lives
repo: coronacheck-upptime # The name of this repository

sites:
  - name: TVS (Login) - OpenID Config
    url: https://tvs.coronacheck.nl/.well-known/openid-configuration
  # - name: TVS (Login) - Heartbeat
  #   url: https://tvs.coronacheck.nl/heartbeat
  - name: TVS (Login) - Authorize
    url: https://tvs.coronacheck.nl/authorize?client_id=cc_web&redirect_uri=https%3A%2F%2Fcoronacheck.nl%2Fnl%2Fprint%2Fjouw-vaccinaties-redirect&response_type=code&scope=openid&state=&code_challenge=&code_challenge_method=S256&response_mode=query&nonce=
  - name: TVS (Login) - Sorry Too Busy
    url: https://tvs.coronacheck.nl/sorry-too-busy?client_id=cc_web&redirect_uri=&state=
  - name: Holder API - Config
    url: https://holder-api.coronacheck.nl/v4/holder/config
  - name: Holder API - Provider config
    url: https://holder-api.coronacheck.nl/v4/holder/config_providers
  - name: Holder API - Convert access tokens
    url: https://holder-api.coronacheck.nl/v4/holder/access_tokens
    expectedStatusCodes:
      - 200
      - 405


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /coronacheck-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CoronaCheck Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
